# Generated by Django 5.2.1 on 2026-05-09 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=120)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='photos_comm_created_074e14_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['photo', 'user'], name='photos_like_photo_i_8d2c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['created_at'], name='photos_phot_created_84134a_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['location'], name='photos_phot_locatio_e50d30_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['author'], name='photos_phot_author__5a9026_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['photo', 'user'], name='photos_rati_photo_i_b178d3_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_entries', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='savedphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='photos_noti_user_id_280e80_idx'),
        ),
        migrations.AddIndex(
            model_name='savedphoto',
            index=models.Index(fields=['user', 'photo'], name='photos_save_user_id_24db10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedphoto',
            unique_together={('photo', 'user')},
        ),
    ]
